import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { PATHS } from "./scripts/paths-config.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  define: {
    BUILD_DEFAULT_SOURCE_PATH: JSON.stringify(PATHS.sourcePath),
    BUILD_DEFAULT_TABLE_PATH: JSON.stringify(PATHS.tablePath),
    BUILD_DEFAULT_ARCHIVE_FOLDER: JSON.stringify(PATHS.archiveFolder),
  },
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
